baseURL = 'https://www.armyrunner77.com/'
languageCode = 'en-us'
title = "AI Creations Showcase Home"
theme = "PaperMod"

[params]
  homeInfoParams = { Title = "Welcome to My AI Showcase", Content = "This site features AI-generated prose, poetry, and more." }
  defaultTheme = "auto"  # Enables light/dark mode toggle
  ShowToc = false        # Hides the Table of Contents for simplicity 

[cascade]
  _build = { list = "page", single = "page", section = "page" }

